### ISSUE TITLE
Update JoatU Invitation Email

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#116]
Please use emailed HTML file (if that works) and be sure to hotlink the invite into the message.

**Comment by undergroundwebdesigns** [comment]
I've done you one (or two) better. I linked the mandril & mailchimp accounts. Now from mailchimp you'll have the option to send a template to Mandrill. Don't do it for all your templates, just ones that, like in this case, the _app_ will be sending. I also realized I needed to specify the language in the link.... so I made two links, the french link opens the app in french, and the english link in english.

Oh, and I also discovered Mandrill supports some advanced anti-spam protection ([DKIM](https://en.wikipedia.org/wiki/DomainKeys_Identified_Mail)), so I set that up. Basically, it's a way of confirming cryptographically that the email we send is actually coming from us, so that should help our messages avoid spam filters.
