### ISSUE TITLE
Create a Pod Homepage

### ISSUE THREAD

**Issue by undergroundwebdesigns** [joatuapp/joatu-v2#57]
Each pod should have it's 'pod homepage' which will display information about the pod, it's hub, and other items of interest to members of the pod. 

For the first round, the pod homepage will have the following:
- [x] Google map, showing the pod's boundaries and Hub location
- [x] The pod has a description text block
- [x] An "upcoming events" text block

**Comment by joatu** [comment]
The *hub should have a description text block (and image or video) which would include hours of operation.

Upcoming Events can (eventually) be linked to Community Offers from people with enough valid references so that they go from being a community even offer to being on the events page seamlessly.

Use Case: I want to offer a guitar lesson at Coop Sur Genereux at 4-6pm on Tuesday. I fill out the offer and submit. The Coop Sur Genereux Organization account gets a notification asking for confirmation if this time slot is available.  Coop Sur Genereux confirms availability, event is then auto-posted into "upcoming events" text block.

**Comment by joatu** [comment]
Hub #1 Coop Sur Genereux
4518 Papineau #3 (alley Genereux)
Hours: 11am-11pm

The cooperative home, now in its twelfth year, is a community intent on creating and maintaining a holistic and harmonious way of life.  Coop Sur Généreux has an open-door policy inviting collaboration, creativity and community building.  They welcome skill-sharing, communal cooking and a safe space for exchange.

Use this image for now as a placeholder.

![_mg_4944](https://cloud.githubusercontent.com/assets/5350076/6101756/7b9acbd6-aff7-11e4-8bb3-bc1de2a0fa59.jpg)

Events listing would also be shown.

French:

Espace #1 Coop Sur Genereux
4518 Papineau #3 (ruelle Genereux)
Heures: 11:00 - 23:00

Une maison coopérative qui depuis douze ans, favorise un mode de vie alternatif. La coop fonctionne autour d'un principe de porte-ouverte qui vise la coopération, la créativité et l'entraide entre les individus et la communauté. Ces valeurs sont mises en action en partageant nos aptitudes, en nourrissant les sans-abris, en accueillant des réunions de groupes communautaires et en fournissant un espace sécuritaire où il est possible d'échanger.

Liste d'événements  <--(List of Events)

**Comment by kyrie08** [comment]
On a formating / layout note, it might be good to do a small subhead like 
**About this user** Une maison coopérative qui depuis douze ans, favorise un mode de vie alternatif. La coop fonctionne autour d'un principe de porte-ouverte qui vise la coopération, la créativité et l'entraide entre les individus et la communauté...

Since people might work with a few users frequently (ie they are in the same area) it can help them skip that section (even more so if information with a recurring nature like that is put in a faintly colored box; or is optional (like you click on the name to see more info in a new blurb))
What kind of blurb depends.. I guess popups are not supported by all browsers. Maybe one of those speech bubbles that come up when you mouseover, disappears when mouseout would be a possibility. Or just have it on a small sidebar.
Depends on the rest of the page.

-Joy

**Comment by joatu** [comment]
*About this hub*  (not user) but that's interesting an interesting point. We might not need to have the reminder of the community hub with every entrance, this is true.  Something to consider. 

Also though, I don't like kijiji's landing page (or craigslists), they're very impersonal, even if they're offering the semblance of practicality.

**Comment by undergroundwebdesigns** [comment]
I'm going to close this, as we have a first draft pod page up, mostly just showing the data we have. Design suggestions extremely welcome, I'll open a new thread for it.
