### ISSUE TITLE
Make Offer/Request Content

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#64]
Please remove Summary and have the summary as the first X words of the description. Maybe we can even say that somewhere...or people will figure it out pretty quick.

Please add Sale/Rent/Trade/Free checkmarks with ________ next to each one so people can explain how much in $ for Sale, how much in caps for trade (or should caps be its own category?  maybe actually...), the cost for renting for x time, etc.

**Comment by joatu** [comment]
Please add Pod/City/World selection into the offers/requests. This will also help tremendously for people who are the first ones in new pods, they'll be able to see other pods offers/requests if they're things that can be done at a distance.

**Comment by undergroundwebdesigns** [comment]
Hey @joatu 

I'm having a look at this today. First impression is that it might be good to have some sort of high-level categories for offers and requests, maybe something along the lines of "skills & time", "physical goods", and "knowledge and information"? Basically then you're offering to do something, provide something, or teach something, respectively, and on the requests side you can differentiate between looking for physical goods, vs professional skills, vs. learning. I think having those categories might help us focus the "payment options" as well (eg, "buying" someones skills doesn't really make sense). At the very least it lets us change the language around those options so that they make more sense in the context of the offer / request.

Speaking of "payment options", I can see this getting quite complicated really quickly, and since JoatU is all about offers / requests, getting these payment options right is going to be important. It seems to me that at a high level there are "one-off", and "time based" offers. Selling or trading something, or teaching a scheduled class (or course) would all be "one-off" offers. Renting out a tool, providing a service, or individual lessons (e.g. Piano), are all time-based, and would be charged per-hour (or per time-period). Some offers might fall into either category, but probably not both at once. For example, I might offer a website package for X$ (one-off) or custom web development for X / hour (time based).

Besides the "one-off" vs "time based" payment, then there's the question of actual currency. What do we support? Canadian dollars, Bitcoin, CAPs? More? How do we handle conversions between these? If someone wants to offer something in all three currencies, do they have to manually enter an amount for all three? What if we later add more currencies... the form gets longer and unwieldy, and adding an offer becomes more work (people are less likely to do it). One possibility is that we could perhaps maintain some suggested conversion rate, so that users enter a value in one currency and the others are auto-populated.

What are your thoughts on this? How do you envision people using this data, and how can we code JoatU to assist with that? The whole point here is not just to let people enter text that we then display back to them, it's to interpret and understand what they enter, so that we can make connections, suggestions, etc. Offers (and especially their payment options) are the one of the first areas where we are really getting into that will have a big effect this way, so they're worth some consideration.

**Comment by undergroundwebdesigns** [comment]
Hey @joatu,

I've pushed a substantial update to the offers / requests system, but there's one page that still really needs a lot of work: the offer detail page. This is the page people see when they click on an offer or a request. As I was thinking of what to put on it, I realized that this is going to be a pivotal part of the site, as this is what people will be looking at to decide whether they want to contact the person and arrange a transaction. So, I figured I'd get your thoughts on what you think we should put on it?

Some ideas I've had
- Information about the offer (title, description, etc). _*obviously*_
- Information about the offer-er, at least name and average rating (from references)?
- If looking at an offer, information about the offer-er's requests, to facilitate trades.
- A link to message the offer-er, with some sort of association to the offer (or maybe just a pre-filled link, for now?) in the message.

Also, any thoughts on how best to lay out this information? Obviously info about the offer itself front and center, maybe user info in a column to the side? And requests underneath? Other suggestions very welcome, just throwing out random ideas here.

Of course, all this would apply to Requests as well, with offers/requests reversed.

**Comment by joatu** [comment]
![img_20150303_223528](https://cloud.githubusercontent.com/assets/5350076/6477824/fe2a8374-c1f5-11e4-9913-76b48d7e8a7e.jpg)

Picture = 1000 words

Great ideas. :)  Let me know if you feel I missed anything or if you think it's too much.

**Comment by undergroundwebdesigns** [comment]
I like it. Bear in mind we have no image support (yet), so I'll leave out the images for now. Also, re: our discussion the other day, we're not going to have the price stuff for now (just the other requests) so your "specific to this offer" section will be blank (for now). I do like the idea of grouping "payment info" with the requests though, as it supports the idea that trading for requests is just as valid.

**Comment by joatu** [comment]
Agreed (re: prices). This was a 'later down the road' kind of drawing.  And a nice big button for sending a message...Or even better, replace the space where there's a big image with a text box to send a message directly!  The more you can do with the fewest clicks = ideal.

**Comment by undergroundwebdesigns** [comment]
While I agree with "the more you can do with fewer clicks", I think putting the message form directly on this page will be too much. We will definitely have a large, prominent button linking to the message page though (and possibly do that in a popup form in the future).

**Comment by joatu** [comment]
That's fine.
